version: "0.1"
services:
  java_api:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo
    restart: always
    ports:
      - 27018:27017